Minor improvements
* Configured death drops in pocket dimensions
* Generated tileset info for the Tesseract Lens

diff --git a/tilesets-add b/tilesets-add
--- a/tilesets-add
+++ b/tilesets-add
@@ -9,12 +9,11 @@ if [ ! -f _metadata ]; then
   exit 1
 fi
 
-if [ ! -r tilesets ]; then
-  ln -s -- "${SB_ASSETS_DIR}/tilesets" .
-elif [ ! -r tilesets/packed ]; then
+mkdir -p tilesets
+
+if [ ! -r tilesets/packed ]; then
   cd tilesets
   ln -s -- "${SB_ASSETS_DIR}/tilesets/packed" .
 else
-  echo 'ERROR: tilesets/packed directory exists. Aborting.' >&2
-  exit 1
+  echo 'ERROR: tilesets/packed directory exists. Skipping.' >&2
 fi
